# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'miCocinaEconomica' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for miCocinaEconomica

  pod 'CalendarKit'	
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'lottie-ios'
  pod 'SDWebImage'
  
  target 'miCocinaEconomicaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'miCocinaEconomicaUITests' do
    # Pods for testing
  end

end
